{{- if .Values.frontend.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: {{ include "ecommerce.fullname" . }}-frontend
    namespace: {{ include "ecommerce.namespace" . }}
    labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ include "ecommerce.fullname" . }}-frontend
    minReplicas: {{ .Values.frontend.autoscaling.minReplicas }}
    maxReplicas: {{ .Values.frontend.autoscaling.maxReplicas }}
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: {{ .Values.frontend.autoscaling.targetCPUUtilizationPercentage }}
        - type: Resource
          resource:
              name: memory
              target:
                  type: Utilization
                  averageUtilization: {{ .Values.frontend.autoscaling.targetMemoryUtilizationPercentage }}
    behavior:
        scaleDown:
            stabilizationWindowSeconds: 300
            policies:
                - type: Percent
                  value: 50
                  periodSeconds: 60
        scaleUp:
            stabilizationWindowSeconds: 0
            policies:
                - type: Percent
                  value: 100
                  periodSeconds: 30
                - type: Pods
                  value: 2
                  periodSeconds: 30
            selectPolicy: Max
{{- end }}
---
{{- if .Values.payment.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: {{ include "ecommerce.fullname" . }}-payment
    namespace: {{ include "ecommerce.namespace" . }}
    labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ include "ecommerce.fullname" . }}-payment
    minReplicas: {{ .Values.payment.autoscaling.minReplicas }}
    maxReplicas: {{ .Values.payment.autoscaling.maxReplicas }}
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: {{ .Values.payment.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
