{{- if .Values.payment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecommerce.fullname" . }}-payment
  namespace: {{ include "ecommerce.namespace" . }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    {{- include "ecommerce.serviceLabels" "payment" | nindent 4 }}
spec:
  replicas: {{ .Values.payment.replicaCount }}
  selector:
    matchLabels:
      {{- include "ecommerce.selectorLabels" . | nindent 6 }}
      app: payment
  template:
    metadata:
      labels:
        {{- include "ecommerce.selectorLabels" . | nindent 8 }}
        app: payment
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ include "ecommerce.serviceAccountName" . }}
      containers:
        - name: payment
          image: {{ include "ecommerce.image" (dict "Values" .Values "image" .Values.payment.image "Chart" .Chart) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.payment.service.port }}
              name: http
          env:
            - name: PORT
              value: "{{ .Values.payment.service.port }}"
            - name: FAILURE_RATE
              value: "{{ .Values.payment.failureRate }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.otel.endpoint }}"
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.payment.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.payment.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 3
          resources:
          {{- toYaml .Values.payment.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce.fullname" . }}-payment
  namespace: {{ include "ecommerce.namespace" . }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    {{- include "ecommerce.serviceLabels" "payment" | nindent 4 }}
spec:
  type: {{ .Values.payment.service.type }}
  ports:
    - port: {{ .Values.payment.service.port }}
      targetPort: {{ .Values.payment.service.port }}
      name: http
  selector:
    {{- include "ecommerce.selectorLabels" . | nindent 4 }}
    app: payment
{{- end }}
