{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ecommerce.serviceAccountName" . }}
  namespace: {{ include "ecommerce.namespace" . }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.observability.prometheus.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ecommerce.fullname" . }}-prometheus
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ecommerce.fullname" . }}-prometheus
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ecommerce.fullname" . }}-prometheus
subjects:
  - kind: ServiceAccount
    name: {{ include "ecommerce.serviceAccountName" . }}
    namespace: {{ include "ecommerce.namespace" . }}
{{- end }}
